#!/usr/bin/with-contenv sh

set -e

# is nebula running for more than 1 sec?
until NEBULA_PID=$(pidof nebula) && [ $(ps -p $NEBULA_PID -o "etimes=") -gt 1 ]; do
	sleep 1
done

CONFIG_FILE=${CONFIG_FILE:-$(ps -p $NEBULA_PID -o "args=" | xargs -n 1 ls 2> /dev/null || :)}
NEBULA_S6_PID=$(ps -p $NEBULA_PID -o "ppid=")
NEBULA_S6_PWD=$(pwdx $NEBULA_S6_PID | awk '{print $NF}')

while watch -g find $CONFIG_DIR $CONFIG_FILE -type f -exec md5sum {} + &> /dev/null; do
	echo "[WARN] Config files have changed. Restarting service..." >&2
	s6-svc -r $NEBULA_S6_PWD
done
