#!/usr/bin/with-contenv sh

CONFIG_FILE=${CONFIG_FILE:-$(find $CONFIG_DIR -iname "*.y*ml" | head -n 1)}

TUN="/dev/net/tun"

if [ ! -e $TUN ]; then
	mkdir -p $(dirname $TUN)
	mknod -m a+w $TUN c 10 200
fi

if ! nebula -test -config $CONFIG_FILE &> /dev/null; then
	cd $(readlink -f $0 | xargs dirname)
	echo -e "Missing/invalid nebula config file.\nAborting.\n$CONFIG_FILE" >&2
	exec s6-svscanctl -b $(dirname $PWD)
else
	cd $(readlink -f $CONFIG_FILE | xargs dirname)
	chmod -R +r $PWD
	exec s6-setuidgid nebula \
		nebula -config $CONFIG_FILE
fi
